# NEXTCLOUD SERVICEACCOUNT
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud
---
# NEXTCLOUD ROLEBINDING
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nextcloud:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: nextcloud
    namespace: <namespace>
---
# NEXTCLOUD VOLUME
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# SMTP SECRET
apiVersion: v1
kind: Secret
metadata:
  name: smtp
stringData:
  HOST: smtp.gmail.com
  SECURE: tls
  PORT: "465"
  NAME: support@heritage.africa
  PASSWORD: <replace>
type: Opaque
---
# NEXTCLOUD SECRET
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
stringData:
  ADMIN_USER: admin
  ADMIN_PASSWORD: nextcloud
type: Opaque
---
# NEXTCLOUD DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      serviceAccountName: nextcloud
      securityContext:
        runAsUser: 0
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
      containers:
        - name: nextcloud
          image: docker.io/s390x/nextcloud:production
          volumeMounts:
            - name: nextcloud
              mountPath: "/var/www/html"
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: postgres-0.postgres
            - name: REDIS_HOST
              value: redis-0.redis
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: <comma seperated list>
            - name: OVERWRITEHOST
              value: <replace>
          envFrom:
            - prefix: POSTGRES_
              secretRef:
                name: postgres
            - prefix: SMTP_
              secretRef:
                name: smtp
            - prefix: NEXTCLOUD_
              secretRef:
                name: nextcloud
---
# NEXTCLOUD SERVICE
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
---
# NEXTCLOUD ROUTE
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  host: <replace>
  port:
    targetPort: 80
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nextcloud
    weight: 100
  wildcardPolicy: None
